/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongodbcrudoperationsreview;

import org.bson.Document;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;

public class App {

    static MongoCollection<Document> itemsCollection;
    static JFrame f;
    static JPanel panel;
    static JPanel ba;
    static JPanel itemList;
    static JButton add;

    private static void start() {
        String uri = "mongodb+srv://nenreh:lol@schoolstuff.gjla1uc.mongodb.net/?retryWrites=true&w=majority&appName=SchoolStuff";
        try (MongoClient mongoClient = MongoClients.create(uri)) {
            MongoDatabase database = mongoClient.getDatabase("Joe");

            itemsCollection = database.getCollection("items");
        }
        //
        f = new JFrame("Joe");
        add = new JButton("money");
        panel = new JPanel();
        ba = new JPanel();
        itemList = new JPanel();

        f.setSize(1200, 700);
        f.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });

        add.setPreferredSize(new Dimension(200, 100));
        add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("clicker");
            }
        });

        panel.setSize(100, 100);
        panel.setBackground(Color.CYAN);
        panel.setLocation(100, 0);
        panel.add(add);

        ba.setLayout(null);
        

        ba.add(itemList);
        ba.add(panel);
        f.add(ba);
    }

    public static void main(String[] args) {
        start();
        f.setVisible(true);
    }
}
